In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [1]:
import numpy as np  
from sklearn.naive_bayes import BernoulliNB
x=np.array([[1,2,3,4],[1,3,4,4],[2,4,5,5],[5,6,9,8]])  
y=np.array([1,1,2,3])

In [2]:
clf=BernoulliNB(alpha=2.0,binarize = 3.0,fit_prior=True)
clf.fit(x,y)

BernoulliNB(alpha=2.0, binarize=3.0)

In [3]:
#训练后学习模型中的参数
print(np.log(2/4))
print(np.log(1/4))
print(np.log(1/4))
print(clf.class_log_prior_)   #对比上面，这是先验概率对数值，类先验概率等于各类的个数/类的总个数

-0.6931471805599453
-1.3862943611198906
-1.3862943611198906
[-0.69314718 -1.38629436 -1.38629436]


In [4]:
print(clf.feature_log_prob_ ) #指定类的各特征概率(条件概率)对数值
print(clf.class_count_)       #按类别顺序输出其对应的个数
print(clf.feature_count_)    

[[-1.09861229 -1.09861229 -0.69314718 -0.40546511]
 [-0.91629073 -0.51082562 -0.51082562 -0.51082562]
 [-0.51082562 -0.51082562 -0.51082562 -0.51082562]]
[2. 1. 1.]
[[0. 0. 1. 2.]
 [0. 1. 1. 1.]
 [1. 1. 1. 1.]]
